language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - llvm-3.9-dev
            - libclang-3.9-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

git:
  submodules: false

before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - llvm-config --includedir
  - ls `llvm-config --includedir`
  - git submodule update --init --recursive -- external/isl
  - git submodule update --init -- external/pet
  - mkdir -p build
script:
  - (cd build; cmake ..)
  - (cd build; make pet)
  - (cd build; make)
  - (cd build; make check)
