language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - llvm-3.9-dev
            - libclang-3.9-dev
      env:
        - MATRIX_EVAL="PATH=`llvm-config-3.9 --bindir`:$PATH"

git:
  submodules: false

before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - llvm-config --includedir
  - ls `llvm-config --includedir`
  - git submodule update --init --recursive -- external/isl
  - git submodule update --init -- external/pet
  - mkdir -p build
script:
  - (cd build; cmake ..)
  - (cd build; make pet)
  - (cd build; make)
  - (cd build; make check)
