# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adilla/Documents/SchedTrees/islutils

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adilla/Documents/SchedTrees/islutils

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adilla/Documents/SchedTrees/islutils/CMakeFiles /home/adilla/Documents/SchedTrees/islutils/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adilla/Documents/SchedTrees/islutils/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named isl

# Build rule for target.
isl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isl
.PHONY : isl

# fast build rule for target.
isl/fast:
	$(MAKE) -f CMakeFiles/isl.dir/build.make CMakeFiles/isl.dir/build
.PHONY : isl/fast

#=============================================================================
# Target rules for targets named pet

# Build rule for target.
pet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pet
.PHONY : pet

# fast build rule for target.
pet/fast:
	$(MAKE) -f CMakeFiles/pet.dir/build.make CMakeFiles/pet.dir/build
.PHONY : pet/fast

#=============================================================================
# Target rules for targets named islutils

# Build rule for target.
islutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 islutils
.PHONY : islutils

# fast build rule for target.
islutils/fast:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/build
.PHONY : islutils/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f external/googletest/googlemock/CMakeFiles/gmock.dir/build.make external/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f external/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make external/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f external/googletest/googlemock/gtest/CMakeFiles/gtest.dir/build.make external/googletest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f external/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make external/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named check-access

# Build rule for target.
check-access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-access
.PHONY : check-access

# fast build rule for target.
check-access/fast:
	$(MAKE) -f test/CMakeFiles/check-access.dir/build.make test/CMakeFiles/check-access.dir/build
.PHONY : check-access/fast

#=============================================================================
# Target rules for targets named check-set_maker

# Build rule for target.
check-set_maker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-set_maker
.PHONY : check-set_maker

# fast build rule for target.
check-set_maker/fast:
	$(MAKE) -f test/CMakeFiles/check-set_maker.dir/build.make test/CMakeFiles/check-set_maker.dir/build
.PHONY : check-set_maker/fast

#=============================================================================
# Target rules for targets named test_builders

# Build rule for target.
test_builders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_builders
.PHONY : test_builders

# fast build rule for target.
test_builders/fast:
	$(MAKE) -f test/CMakeFiles/test_builders.dir/build.make test/CMakeFiles/test_builders.dir/build
.PHONY : test_builders/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f test/CMakeFiles/check.dir/build.make test/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named check-builders

# Build rule for target.
check-builders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-builders
.PHONY : check-builders

# fast build rule for target.
check-builders/fast:
	$(MAKE) -f test/CMakeFiles/check-builders.dir/build.make test/CMakeFiles/check-builders.dir/build
.PHONY : check-builders/fast

#=============================================================================
# Target rules for targets named test_transformer

# Build rule for target.
test_transformer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_transformer
.PHONY : test_transformer

# fast build rule for target.
test_transformer/fast:
	$(MAKE) -f test/CMakeFiles/test_transformer.dir/build.make test/CMakeFiles/test_transformer.dir/build
.PHONY : test_transformer/fast

#=============================================================================
# Target rules for targets named ppcg

# Build rule for target.
ppcg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppcg
.PHONY : ppcg

# fast build rule for target.
ppcg/fast:
	$(MAKE) -f test/CMakeFiles/ppcg.dir/build.make test/CMakeFiles/ppcg.dir/build
.PHONY : ppcg/fast

#=============================================================================
# Target rules for targets named test_set_maker

# Build rule for target.
test_set_maker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_set_maker
.PHONY : test_set_maker

# fast build rule for target.
test_set_maker/fast:
	$(MAKE) -f test/CMakeFiles/test_set_maker.dir/build.make test/CMakeFiles/test_set_maker.dir/build
.PHONY : test_set_maker/fast

#=============================================================================
# Target rules for targets named check-transformer

# Build rule for target.
check-transformer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-transformer
.PHONY : check-transformer

# fast build rule for target.
check-transformer/fast:
	$(MAKE) -f test/CMakeFiles/check-transformer.dir/build.make test/CMakeFiles/check-transformer.dir/build
.PHONY : check-transformer/fast

#=============================================================================
# Target rules for targets named test_access

# Build rule for target.
test_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_access
.PHONY : test_access

# fast build rule for target.
test_access/fast:
	$(MAKE) -f test/CMakeFiles/test_access.dir/build.make test/CMakeFiles/test_access.dir/build
.PHONY : test_access/fast

#=============================================================================
# Target rules for targets named test_matcher

# Build rule for target.
test_matcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_matcher
.PHONY : test_matcher

# fast build rule for target.
test_matcher/fast:
	$(MAKE) -f test/CMakeFiles/test_matcher.dir/build.make test/CMakeFiles/test_matcher.dir/build
.PHONY : test_matcher/fast

#=============================================================================
# Target rules for targets named check-matcher

# Build rule for target.
check-matcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-matcher
.PHONY : check-matcher

# fast build rule for target.
check-matcher/fast:
	$(MAKE) -f test/CMakeFiles/check-matcher.dir/build.make test/CMakeFiles/check-matcher.dir/build
.PHONY : check-matcher/fast

islutils/access_patterns.o: islutils/access_patterns.cc.o

.PHONY : islutils/access_patterns.o

# target to build an object file
islutils/access_patterns.cc.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/access_patterns.cc.o
.PHONY : islutils/access_patterns.cc.o

islutils/access_patterns.i: islutils/access_patterns.cc.i

.PHONY : islutils/access_patterns.i

# target to preprocess a source file
islutils/access_patterns.cc.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/access_patterns.cc.i
.PHONY : islutils/access_patterns.cc.i

islutils/access_patterns.s: islutils/access_patterns.cc.s

.PHONY : islutils/access_patterns.s

# target to generate assembly for a file
islutils/access_patterns.cc.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/access_patterns.cc.s
.PHONY : islutils/access_patterns.cc.s

islutils/builders.o: islutils/builders.cc.o

.PHONY : islutils/builders.o

# target to build an object file
islutils/builders.cc.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/builders.cc.o
.PHONY : islutils/builders.cc.o

islutils/builders.i: islutils/builders.cc.i

.PHONY : islutils/builders.i

# target to preprocess a source file
islutils/builders.cc.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/builders.cc.i
.PHONY : islutils/builders.cc.i

islutils/builders.s: islutils/builders.cc.s

.PHONY : islutils/builders.s

# target to generate assembly for a file
islutils/builders.cc.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/builders.cc.s
.PHONY : islutils/builders.cc.s

islutils/cpu.o: islutils/cpu.c.o

.PHONY : islutils/cpu.o

# target to build an object file
islutils/cpu.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cpu.c.o
.PHONY : islutils/cpu.c.o

islutils/cpu.i: islutils/cpu.c.i

.PHONY : islutils/cpu.i

# target to preprocess a source file
islutils/cpu.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cpu.c.i
.PHONY : islutils/cpu.c.i

islutils/cpu.s: islutils/cpu.c.s

.PHONY : islutils/cpu.s

# target to generate assembly for a file
islutils/cpu.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cpu.c.s
.PHONY : islutils/cpu.c.s

islutils/cuda.o: islutils/cuda.c.o

.PHONY : islutils/cuda.o

# target to build an object file
islutils/cuda.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cuda.c.o
.PHONY : islutils/cuda.c.o

islutils/cuda.i: islutils/cuda.c.i

.PHONY : islutils/cuda.i

# target to preprocess a source file
islutils/cuda.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cuda.c.i
.PHONY : islutils/cuda.c.i

islutils/cuda.s: islutils/cuda.c.s

.PHONY : islutils/cuda.s

# target to generate assembly for a file
islutils/cuda.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cuda.c.s
.PHONY : islutils/cuda.c.s

islutils/cuda_common.o: islutils/cuda_common.c.o

.PHONY : islutils/cuda_common.o

# target to build an object file
islutils/cuda_common.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cuda_common.c.o
.PHONY : islutils/cuda_common.c.o

islutils/cuda_common.i: islutils/cuda_common.c.i

.PHONY : islutils/cuda_common.i

# target to preprocess a source file
islutils/cuda_common.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cuda_common.c.i
.PHONY : islutils/cuda_common.c.i

islutils/cuda_common.s: islutils/cuda_common.c.s

.PHONY : islutils/cuda_common.s

# target to generate assembly for a file
islutils/cuda_common.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/cuda_common.c.s
.PHONY : islutils/cuda_common.c.s

islutils/gpu.o: islutils/gpu.c.o

.PHONY : islutils/gpu.o

# target to build an object file
islutils/gpu.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu.c.o
.PHONY : islutils/gpu.c.o

islutils/gpu.i: islutils/gpu.c.i

.PHONY : islutils/gpu.i

# target to preprocess a source file
islutils/gpu.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu.c.i
.PHONY : islutils/gpu.c.i

islutils/gpu.s: islutils/gpu.c.s

.PHONY : islutils/gpu.s

# target to generate assembly for a file
islutils/gpu.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu.c.s
.PHONY : islutils/gpu.c.s

islutils/gpu_array_tile.o: islutils/gpu_array_tile.c.o

.PHONY : islutils/gpu_array_tile.o

# target to build an object file
islutils/gpu_array_tile.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_array_tile.c.o
.PHONY : islutils/gpu_array_tile.c.o

islutils/gpu_array_tile.i: islutils/gpu_array_tile.c.i

.PHONY : islutils/gpu_array_tile.i

# target to preprocess a source file
islutils/gpu_array_tile.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_array_tile.c.i
.PHONY : islutils/gpu_array_tile.c.i

islutils/gpu_array_tile.s: islutils/gpu_array_tile.c.s

.PHONY : islutils/gpu_array_tile.s

# target to generate assembly for a file
islutils/gpu_array_tile.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_array_tile.c.s
.PHONY : islutils/gpu_array_tile.c.s

islutils/gpu_group.o: islutils/gpu_group.c.o

.PHONY : islutils/gpu_group.o

# target to build an object file
islutils/gpu_group.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_group.c.o
.PHONY : islutils/gpu_group.c.o

islutils/gpu_group.i: islutils/gpu_group.c.i

.PHONY : islutils/gpu_group.i

# target to preprocess a source file
islutils/gpu_group.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_group.c.i
.PHONY : islutils/gpu_group.c.i

islutils/gpu_group.s: islutils/gpu_group.c.s

.PHONY : islutils/gpu_group.s

# target to generate assembly for a file
islutils/gpu_group.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_group.c.s
.PHONY : islutils/gpu_group.c.s

islutils/gpu_hybrid.o: islutils/gpu_hybrid.c.o

.PHONY : islutils/gpu_hybrid.o

# target to build an object file
islutils/gpu_hybrid.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_hybrid.c.o
.PHONY : islutils/gpu_hybrid.c.o

islutils/gpu_hybrid.i: islutils/gpu_hybrid.c.i

.PHONY : islutils/gpu_hybrid.i

# target to preprocess a source file
islutils/gpu_hybrid.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_hybrid.c.i
.PHONY : islutils/gpu_hybrid.c.i

islutils/gpu_hybrid.s: islutils/gpu_hybrid.c.s

.PHONY : islutils/gpu_hybrid.s

# target to generate assembly for a file
islutils/gpu_hybrid.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_hybrid.c.s
.PHONY : islutils/gpu_hybrid.c.s

islutils/gpu_print.o: islutils/gpu_print.c.o

.PHONY : islutils/gpu_print.o

# target to build an object file
islutils/gpu_print.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_print.c.o
.PHONY : islutils/gpu_print.c.o

islutils/gpu_print.i: islutils/gpu_print.c.i

.PHONY : islutils/gpu_print.i

# target to preprocess a source file
islutils/gpu_print.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_print.c.i
.PHONY : islutils/gpu_print.c.i

islutils/gpu_print.s: islutils/gpu_print.c.s

.PHONY : islutils/gpu_print.s

# target to generate assembly for a file
islutils/gpu_print.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_print.c.s
.PHONY : islutils/gpu_print.c.s

islutils/gpu_tree.o: islutils/gpu_tree.c.o

.PHONY : islutils/gpu_tree.o

# target to build an object file
islutils/gpu_tree.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_tree.c.o
.PHONY : islutils/gpu_tree.c.o

islutils/gpu_tree.i: islutils/gpu_tree.c.i

.PHONY : islutils/gpu_tree.i

# target to preprocess a source file
islutils/gpu_tree.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_tree.c.i
.PHONY : islutils/gpu_tree.c.i

islutils/gpu_tree.s: islutils/gpu_tree.c.s

.PHONY : islutils/gpu_tree.s

# target to generate assembly for a file
islutils/gpu_tree.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/gpu_tree.c.s
.PHONY : islutils/gpu_tree.c.s

islutils/grouping.o: islutils/grouping.c.o

.PHONY : islutils/grouping.o

# target to build an object file
islutils/grouping.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/grouping.c.o
.PHONY : islutils/grouping.c.o

islutils/grouping.i: islutils/grouping.c.i

.PHONY : islutils/grouping.i

# target to preprocess a source file
islutils/grouping.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/grouping.c.i
.PHONY : islutils/grouping.c.i

islutils/grouping.s: islutils/grouping.c.s

.PHONY : islutils/grouping.s

# target to generate assembly for a file
islutils/grouping.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/grouping.c.s
.PHONY : islutils/grouping.c.s

islutils/hybrid.o: islutils/hybrid.c.o

.PHONY : islutils/hybrid.o

# target to build an object file
islutils/hybrid.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/hybrid.c.o
.PHONY : islutils/hybrid.c.o

islutils/hybrid.i: islutils/hybrid.c.i

.PHONY : islutils/hybrid.i

# target to preprocess a source file
islutils/hybrid.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/hybrid.c.i
.PHONY : islutils/hybrid.c.i

islutils/hybrid.s: islutils/hybrid.c.s

.PHONY : islutils/hybrid.s

# target to generate assembly for a file
islutils/hybrid.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/hybrid.c.s
.PHONY : islutils/hybrid.c.s

islutils/matchers.o: islutils/matchers.cc.o

.PHONY : islutils/matchers.o

# target to build an object file
islutils/matchers.cc.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/matchers.cc.o
.PHONY : islutils/matchers.cc.o

islutils/matchers.i: islutils/matchers.cc.i

.PHONY : islutils/matchers.i

# target to preprocess a source file
islutils/matchers.cc.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/matchers.cc.i
.PHONY : islutils/matchers.cc.i

islutils/matchers.s: islutils/matchers.cc.s

.PHONY : islutils/matchers.s

# target to generate assembly for a file
islutils/matchers.cc.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/matchers.cc.s
.PHONY : islutils/matchers.cc.s

islutils/opencl.o: islutils/opencl.c.o

.PHONY : islutils/opencl.o

# target to build an object file
islutils/opencl.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/opencl.c.o
.PHONY : islutils/opencl.c.o

islutils/opencl.i: islutils/opencl.c.i

.PHONY : islutils/opencl.i

# target to preprocess a source file
islutils/opencl.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/opencl.c.i
.PHONY : islutils/opencl.c.i

islutils/opencl.s: islutils/opencl.c.s

.PHONY : islutils/opencl.s

# target to generate assembly for a file
islutils/opencl.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/opencl.c.s
.PHONY : islutils/opencl.c.s

islutils/pet_wrapper.o: islutils/pet_wrapper.cc.o

.PHONY : islutils/pet_wrapper.o

# target to build an object file
islutils/pet_wrapper.cc.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/pet_wrapper.cc.o
.PHONY : islutils/pet_wrapper.cc.o

islutils/pet_wrapper.i: islutils/pet_wrapper.cc.i

.PHONY : islutils/pet_wrapper.i

# target to preprocess a source file
islutils/pet_wrapper.cc.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/pet_wrapper.cc.i
.PHONY : islutils/pet_wrapper.cc.i

islutils/pet_wrapper.s: islutils/pet_wrapper.cc.s

.PHONY : islutils/pet_wrapper.s

# target to generate assembly for a file
islutils/pet_wrapper.cc.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/pet_wrapper.cc.s
.PHONY : islutils/pet_wrapper.cc.s

islutils/ppcg.o: islutils/ppcg.c.o

.PHONY : islutils/ppcg.o

# target to build an object file
islutils/ppcg.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/ppcg.c.o
.PHONY : islutils/ppcg.c.o

islutils/ppcg.i: islutils/ppcg.c.i

.PHONY : islutils/ppcg.i

# target to preprocess a source file
islutils/ppcg.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/ppcg.c.i
.PHONY : islutils/ppcg.c.i

islutils/ppcg.s: islutils/ppcg.c.s

.PHONY : islutils/ppcg.s

# target to generate assembly for a file
islutils/ppcg.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/ppcg.c.s
.PHONY : islutils/ppcg.c.s

islutils/ppcg_options.o: islutils/ppcg_options.c.o

.PHONY : islutils/ppcg_options.o

# target to build an object file
islutils/ppcg_options.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/ppcg_options.c.o
.PHONY : islutils/ppcg_options.c.o

islutils/ppcg_options.i: islutils/ppcg_options.c.i

.PHONY : islutils/ppcg_options.i

# target to preprocess a source file
islutils/ppcg_options.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/ppcg_options.c.i
.PHONY : islutils/ppcg_options.c.i

islutils/ppcg_options.s: islutils/ppcg_options.c.s

.PHONY : islutils/ppcg_options.s

# target to generate assembly for a file
islutils/ppcg_options.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/ppcg_options.c.s
.PHONY : islutils/ppcg_options.c.s

islutils/print.o: islutils/print.c.o

.PHONY : islutils/print.o

# target to build an object file
islutils/print.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/print.c.o
.PHONY : islutils/print.c.o

islutils/print.i: islutils/print.c.i

.PHONY : islutils/print.i

# target to preprocess a source file
islutils/print.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/print.c.i
.PHONY : islutils/print.c.i

islutils/print.s: islutils/print.c.s

.PHONY : islutils/print.s

# target to generate assembly for a file
islutils/print.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/print.c.s
.PHONY : islutils/print.c.s

islutils/schedule.o: islutils/schedule.c.o

.PHONY : islutils/schedule.o

# target to build an object file
islutils/schedule.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/schedule.c.o
.PHONY : islutils/schedule.c.o

islutils/schedule.i: islutils/schedule.c.i

.PHONY : islutils/schedule.i

# target to preprocess a source file
islutils/schedule.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/schedule.c.i
.PHONY : islutils/schedule.c.i

islutils/schedule.s: islutils/schedule.c.s

.PHONY : islutils/schedule.s

# target to generate assembly for a file
islutils/schedule.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/schedule.c.s
.PHONY : islutils/schedule.c.s

islutils/util.o: islutils/util.c.o

.PHONY : islutils/util.o

# target to build an object file
islutils/util.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/util.c.o
.PHONY : islutils/util.c.o

islutils/util.i: islutils/util.c.i

.PHONY : islutils/util.i

# target to preprocess a source file
islutils/util.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/util.c.i
.PHONY : islutils/util.c.i

islutils/util.s: islutils/util.c.s

.PHONY : islutils/util.s

# target to generate assembly for a file
islutils/util.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/util.c.s
.PHONY : islutils/util.c.s

islutils/version.o: islutils/version.c.o

.PHONY : islutils/version.o

# target to build an object file
islutils/version.c.o:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/version.c.o
.PHONY : islutils/version.c.o

islutils/version.i: islutils/version.c.i

.PHONY : islutils/version.i

# target to preprocess a source file
islutils/version.c.i:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/version.c.i
.PHONY : islutils/version.c.i

islutils/version.s: islutils/version.c.s

.PHONY : islutils/version.s

# target to generate assembly for a file
islutils/version.c.s:
	$(MAKE) -f CMakeFiles/islutils.dir/build.make CMakeFiles/islutils.dir/islutils/version.c.s
.PHONY : islutils/version.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... isl"
	@echo "... rebuild_cache"
	@echo "... pet"
	@echo "... install/local"
	@echo "... islutils"
	@echo "... install/strip"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... check-access"
	@echo "... check-set_maker"
	@echo "... test_builders"
	@echo "... check"
	@echo "... check-builders"
	@echo "... test_transformer"
	@echo "... ppcg"
	@echo "... test_set_maker"
	@echo "... check-transformer"
	@echo "... test_access"
	@echo "... test_matcher"
	@echo "... check-matcher"
	@echo "... islutils/access_patterns.o"
	@echo "... islutils/access_patterns.i"
	@echo "... islutils/access_patterns.s"
	@echo "... islutils/builders.o"
	@echo "... islutils/builders.i"
	@echo "... islutils/builders.s"
	@echo "... islutils/cpu.o"
	@echo "... islutils/cpu.i"
	@echo "... islutils/cpu.s"
	@echo "... islutils/cuda.o"
	@echo "... islutils/cuda.i"
	@echo "... islutils/cuda.s"
	@echo "... islutils/cuda_common.o"
	@echo "... islutils/cuda_common.i"
	@echo "... islutils/cuda_common.s"
	@echo "... islutils/gpu.o"
	@echo "... islutils/gpu.i"
	@echo "... islutils/gpu.s"
	@echo "... islutils/gpu_array_tile.o"
	@echo "... islutils/gpu_array_tile.i"
	@echo "... islutils/gpu_array_tile.s"
	@echo "... islutils/gpu_group.o"
	@echo "... islutils/gpu_group.i"
	@echo "... islutils/gpu_group.s"
	@echo "... islutils/gpu_hybrid.o"
	@echo "... islutils/gpu_hybrid.i"
	@echo "... islutils/gpu_hybrid.s"
	@echo "... islutils/gpu_print.o"
	@echo "... islutils/gpu_print.i"
	@echo "... islutils/gpu_print.s"
	@echo "... islutils/gpu_tree.o"
	@echo "... islutils/gpu_tree.i"
	@echo "... islutils/gpu_tree.s"
	@echo "... islutils/grouping.o"
	@echo "... islutils/grouping.i"
	@echo "... islutils/grouping.s"
	@echo "... islutils/hybrid.o"
	@echo "... islutils/hybrid.i"
	@echo "... islutils/hybrid.s"
	@echo "... islutils/matchers.o"
	@echo "... islutils/matchers.i"
	@echo "... islutils/matchers.s"
	@echo "... islutils/opencl.o"
	@echo "... islutils/opencl.i"
	@echo "... islutils/opencl.s"
	@echo "... islutils/pet_wrapper.o"
	@echo "... islutils/pet_wrapper.i"
	@echo "... islutils/pet_wrapper.s"
	@echo "... islutils/ppcg.o"
	@echo "... islutils/ppcg.i"
	@echo "... islutils/ppcg.s"
	@echo "... islutils/ppcg_options.o"
	@echo "... islutils/ppcg_options.i"
	@echo "... islutils/ppcg_options.s"
	@echo "... islutils/print.o"
	@echo "... islutils/print.i"
	@echo "... islutils/print.s"
	@echo "... islutils/schedule.o"
	@echo "... islutils/schedule.i"
	@echo "... islutils/schedule.s"
	@echo "... islutils/util.o"
	@echo "... islutils/util.i"
	@echo "... islutils/util.s"
	@echo "... islutils/version.o"
	@echo "... islutils/version.i"
	@echo "... islutils/version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

